//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string AccountCreationError {
            get {
                return ResourceManager.GetString("AccountCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event to your calendar:.
        /// </summary>
        public static string AddEventToCalendar {
            get {
                return ResourceManager.GetString("AddEventToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Facebook.
        /// </summary>
        public static string AddToFacebook {
            get {
                return ResourceManager.GetString("AddToFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Google Buzz.
        /// </summary>
        public static string AddToGoogleBuzz {
            get {
                return ResourceManager.GetString("AddToGoogleBuzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string ampm {
            get {
                return ResourceManager.GetString("ampm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a huge nerd? Perhaps a geek? No? Maybe a dork, dweeb or wonk.
        ///    Quite possibly you&apos;re just a normal person. Either way, you&apos;re a social being. You need to get out for a bite
        ///    to eat occasionally, preferably with folks that are like you..
        /// </summary>
        public static string AreYouHugeNerd {
            get {
                return ResourceManager.GetString("AreYouHugeNerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string atAddress {
            get {
                return ResourceManager.GetString("atAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps returned the address &apos;{0}&apos; for the pin location. Click &apos;OK&apos; to use this address for the event, or &apos;Cancel&apos; to use the current address of &apos;{1}&apos;.
        /// </summary>
        public static string BingMapsReturnedAddress {
            get {
                return ResourceManager.GetString("BingMapsReturnedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel your RSVP.
        /// </summary>
        public static string CancelYourRSVP {
            get {
                return ResourceManager.GetString("CancelYourRSVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for Upcoming Dinners.
        /// </summary>
        public static string ClickForUpcomingDinner {
            get {
                return ResourceManager.GetString("ClickForUpcomingDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have logged in previously, click the same button you did last time!!.
        /// </summary>
        public static string ClickSameButton {
            get {
                return ResourceManager.GetString("ClickSameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string closeText {
            get {
                return ResourceManager.GetString("closeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password:.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string CurrentPasswordInvalid {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string currentText {
            get {
                return ResourceManager.GetString("currentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Dinner.
        /// </summary>
        public static string DeleteDinner {
            get {
                return ResourceManager.GetString("DeleteDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner Deleted.
        /// </summary>
        public static string DinnerDeleted {
            get {
                return ResourceManager.GetString("DinnerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry - but the dinner you requested doesn&apos;t exist or was deleted..
        /// </summary>
        public static string DinnerDoesntExist {
            get {
                return ResourceManager.GetString("DinnerDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinners Near You.
        /// </summary>
        public static string DinnersNearYou {
            get {
                return ResourceManager.GetString("DinnersNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} on {2}.
        /// </summary>
        public static string DinnerWithOn {
            get {
                return ResourceManager.GetString("DinnerWithOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} on {2:MMM dd, yyyy} at {3}. Where: {4}, {5}.
        /// </summary>
        public static string DinnerWithOnAtWhere {
            get {
                return ResourceManager.GetString("DinnerWithOnAtWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (drag the pin in the map if it doesn&apos;t look right) *.
        /// </summary>
        public static string DragThePin {
            get {
                return ResourceManager.GetString("DragThePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit: .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Dinner.
        /// </summary>
        public static string EditDinner {
            get {
                return ResourceManager.GetString("EditDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string EnterDifferentEmail {
            get {
                return ResourceManager.GetString("EnterDifferentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &lt;a href=&quot;http://www.nerddinner.com&quot;&gt;NerdDinner.com&lt;/a&gt;, for all your event planning needs. We&apos;re focused on one thing. Organizing the world&apos;s
        ///    nerds and helping them eat in packs..
        /// </summary>
        public static string EnterForEventNeeds {
            get {
                return ResourceManager.GetString("EnterForEventNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string EnterUsernamePassword {
            get {
                return ResourceManager.GetString("EnterUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your location or.
        /// </summary>
        public static string EnterYourLocation {
            get {
                return ResourceManager.GetString("EnterYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Accessing Dinner.
        /// </summary>
        public static string ErrorAccessingDinner {
            get {
                return ResourceManager.GetString("ErrorAccessingDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request. We&apos;ve been notified and we will check it out. If you know what you were doing, or if you&apos;re evil, let us know on our &lt;a href=&quot;http://feedback.nerddiner.com&quot;&gt;feedback site.&lt;/a&gt;.
        /// </summary>
        public static string ErrorOcurred {
            get {
                return ResourceManager.GetString("ErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback site.
        /// </summary>
        public static string FeedbackSite {
            get {
                return ResourceManager.GetString("FeedbackSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Dinner.
        /// </summary>
        public static string FindADinner {
            get {
                return ResourceManager.GetString("FindADinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Dinner.
        /// </summary>
        public static string FindDinner {
            get {
                return ResourceManager.GetString("FindDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Nerd Dinner near you!.
        /// </summary>
        public static string FindNerdDinnerNearYou {
            get {
                return ResourceManager.GetString("FindNerdDinnerNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a Dinner.
        /// </summary>
        public static string HostADinner {
            get {
                return ResourceManager.GetString("HostADinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Dinner.
        /// </summary>
        public static string HostDinner {
            get {
                return ResourceManager.GetString("HostDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a Nerd Dinner.
        /// </summary>
        public static string HostNerdDinner {
            get {
                return ResourceManager.GetString("HostNerdDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string hourText {
            get {
                return ResourceManager.GetString("hourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string IfYouDontHaveAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you canceled login at your OpenID Provider..
        /// </summary>
        public static string ItLooksYouCanceledOpenId {
            get {
                return ResourceManager.GetString("ItLooksYouCanceledOpenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code by &lt;a href=&quot;http://www.hanselman.com&quot;&gt;Hanselman&lt;/a&gt;, &lt;a href=&quot;http://weblogs.asp.net/scottgu&quot;&gt;
        ///               Guthrie&lt;/a&gt;, &lt;a href=&quot;http://weblogs.asp.net/jgalloway&quot;&gt;Galloway&lt;/a&gt;, &lt;a href=&quot;http://blog.wekeroad.com&quot;&gt;
        ///                   Conery&lt;/a&gt; and &lt;a href=&quot;http://blog.nerdbank.net/&quot;&gt;Arnott&lt;/a&gt;. JavaScript
        ///           by &lt;a href=&quot;http://encosia.com&quot;&gt;Dave Ward&lt;/a&gt;. ASP.NET MVC by &lt;a href=&quot;http://www.haacked.com&quot;&gt;
        ///               Haack&lt;/a&gt; and friends. Style by &lt;a href=&quot;http://michaeldorian.com/&quot;&gt;Mich [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LayoutFooter {
            get {
                return ResourceManager.GetString("LayoutFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerd Dinner - Organizing the world&apos;s nerds and helping them eat in packs.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like there&apos;s no Nerd Dinners near {0} in the near future..
        /// </summary>
        public static string LooksLikeNoDinners {
            get {
                return ResourceManager.GetString("LooksLikeNoDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost?.
        /// </summary>
        public static string LostQuestion {
            get {
                return ResourceManager.GetString("LostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string MinNewPasswordLength {
            get {
                return ResourceManager.GetString("MinNewPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string MinPasswordLength {
            get {
                return ResourceManager.GetString("MinPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string minuteText {
            get {
                return ResourceManager.GetString("minuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd.
        /// </summary>
        public static string MMMdd {
            get {
                return ResourceManager.GetString("MMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        public static string MMMddcyyyy {
            get {
                return ResourceManager.GetString("MMMddcyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address may not be longer than 50 characters.
        /// </summary>
        public static string ModelAdderssTooLong {
            get {
                return ResourceManager.GetString("ModelAdderssTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address, City, State, ZIP.
        /// </summary>
        public static string ModelAddress {
            get {
                return ResourceManager.GetString("ModelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string ModelAddressRequired {
            get {
                return ResourceManager.GetString("ModelAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string ModelConfirmPassword {
            get {
                return ResourceManager.GetString("ModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ModelContactInfo {
            get {
                return ResourceManager.GetString("ModelContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone is required.
        /// </summary>
        public static string ModelContactPhoneRequired {
            get {
                return ResourceManager.GetString("ModelContactPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone may not be longer than 20 characters.
        /// </summary>
        public static string ModelContactPhoneTooLong {
            get {
                return ResourceManager.GetString("ModelContactPhoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ModelCountry {
            get {
                return ResourceManager.GetString("ModelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string ModelDescriptionRequired {
            get {
                return ResourceManager.GetString("ModelDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description may not be longer than 256 characters.
        /// </summary>
        public static string ModelDescriptionTooLong {
            get {
                return ResourceManager.GetString("ModelDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string ModelEmail {
            get {
                return ResourceManager.GetString("ModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string ModelEventDate {
            get {
                return ResourceManager.GetString("ModelEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date is required.
        /// </summary>
        public static string ModelEventDateRequired {
            get {
                return ResourceManager.GetString("ModelEventDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted By name may not be longer than 20 characters.
        /// </summary>
        public static string ModelHostedByTooLong {
            get {
                return ResourceManager.GetString("ModelHostedByTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host&apos;s Name.
        /// </summary>
        public static string ModelHostName {
            get {
                return ResourceManager.GetString("ModelHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string ModelPassword {
            get {
                return ResourceManager.GetString("ModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ModelRegister {
            get {
                return ResourceManager.GetString("ModelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string ModelRememberMe {
            get {
                return ResourceManager.GetString("ModelRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ModelTitle {
            get {
                return ResourceManager.GetString("ModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string ModelTitleRequired {
            get {
                return ResourceManager.GetString("ModelTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title may not be longer than 50 characters.
        /// </summary>
        public static string ModelTitleTooLong {
            get {
                return ResourceManager.GetString("ModelTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string ModelUsername {
            get {
                return ResourceManager.GetString("ModelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM d, yyyy.
        /// </summary>
        public static string MonthDayYear {
            get {
                return ResourceManager.GetString("MonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More dinners and fun at.
        /// </summary>
        public static string MoreDinnersAndFunAt {
            get {
                return ResourceManager.GetString("MoreDinnersAndFunAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dinners.
        /// </summary>
        public static string MyDinners {
            get {
                return ResourceManager.GetString("MyDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerd Dinner.
        /// </summary>
        public static string NerdDinner {
            get {
                return ResourceManager.GetString("NerdDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerd Dinner Not Found.
        /// </summary>
        public static string NerdDinnerNotFound {
            get {
                return ResourceManager.GetString("NerdDinnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerd Dinners.
        /// </summary>
        public static string NerdDinners {
            get {
                return ResourceManager.GetString("NerdDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string NewPasswordAndConfirmationMismatch {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dinner found for that id.
        /// </summary>
        public static string NoDinnerFoundForId {
            get {
                return ResourceManager.GetString("NoDinnerFoundForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dinner found due to invalid dinner id.
        /// </summary>
        public static string NoDinnerFoundInvalidId {
            get {
                return ResourceManager.GetString("NoDinnerFoundInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Nerd Dinners found!.
        /// </summary>
        public static string NoNerdDinnersFound {
            get {
                return ResourceManager.GetString("NoNerdDinnersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one has registered..
        /// </summary>
        public static string NoOneHasRegistered {
            get {
                return ResourceManager.GetString("NoOneHasRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Twitter OAuth consumer key and secret could be found in web.config AppSettings..
        /// </summary>
        public static string NoTwitterKeyFound {
            get {
                return ResourceManager.GetString("NoTwitterKeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!.
        /// </summary>
        public static string OhSnap {
            get {
                return ResourceManager.GetString("OhSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry - but only the host of a Dinner can edit or delete it..
        /// </summary>
        public static string OnlyHostCanEditDelete {
            get {
                return ResourceManager.GetString("OnlyHostCanEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer:.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string PageNext {
            get {
                return ResourceManager.GetString("PageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Prev.
        /// </summary>
        public static string PagePrev {
            get {
                return ResourceManager.GetString("PagePrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string PasswordChangeError {
            get {
                return ResourceManager.GetString("PasswordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordSuccess {
            get {
                return ResourceManager.GetString("PasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password of {2} or more characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture of a huge nerd..
        /// </summary>
        public static string PictureOfHugeNerd {
            get {
                return ResourceManager.GetString("PictureOfHugeNerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you want to cancel the dinner titled:.
        /// </summary>
        public static string PleaseConfirmCancelDinner {
            get {
                return ResourceManager.GetString("PleaseConfirmCancelDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string PleaseCorrectErrors {
            get {
                return ResourceManager.GetString("PleaseCorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Dinners.
        /// </summary>
        public static string PopularDinners {
            get {
                return ResourceManager.GetString("PopularDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will never sell or give away anything of yours that we have. Honest..
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivacyPolicy.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for an account.
        /// </summary>
        public static string RegisterForAccount {
            get {
                return ResourceManager.GetString("RegisterForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVP.
        /// </summary>
        public static string RSVP {
            get {
                return ResourceManager.GetString("RSVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVP for this event.
        /// </summary>
        public static string RsvpForThisEvent {
            get {
                return ResourceManager.GetString("RsvpForThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVPs.
        /// </summary>
        public static string RSVPs {
            get {
                return ResourceManager.GetString("RSVPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string secondText {
            get {
                return ResourceManager.GetString("secondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share:.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you can&apos;t make it!.
        /// </summary>
        public static string SorryYouCantMakeIt {
            get {
                return ResourceManager.GetString("SorryYouCantMakeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks - we&apos;ll see you there!.
        /// </summary>
        public static string ThanksSeeYouThere {
            get {
                return ResourceManager.GetString("ThanksSeeYouThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Time.
        /// </summary>
        public static string timeOnlyTitle {
            get {
                return ResourceManager.GetString("timeOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string timeText {
            get {
                return ResourceManager.GetString("timeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet this.
        /// </summary>
        public static string TweetThis {
            get {
                return ResourceManager.GetString("TweetThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Dinners.
        /// </summary>
        public static string UpcomingDinners {
            get {
                return ResourceManager.GetString("UpcomingDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Nerd Dinners.
        /// </summary>
        public static string UpcomingNerdDinners {
            get {
                return ResourceManager.GetString("UpcomingNerdDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        public static string UseFormBelow {
            get {
                return ResourceManager.GetString("UseFormBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        public static string UseFormChangePassword {
            get {
                return ResourceManager.GetString("UseFormChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using a NerdDinner account.
        /// </summary>
        public static string UsingNerdDinnerAccount {
            get {
                return ResourceManager.GetString("UsingNerdDinnerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via 3rd Party (recommended).
        /// </summary>
        public static string Via3rdParty {
            get {
                return ResourceManager.GetString("Via3rdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Upcoming Dinners.
        /// </summary>
        public static string ViewUpcomingDinners {
            get {
                return ResourceManager.GetString("ViewUpcomingDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re free and fun. &lt;a href=&quot;{0}&quot;&gt;Find a dinner near you&lt;/a&gt;, or &lt;a href=&quot;{1}&quot;&gt;host a dinner&lt;/a&gt;. Be social..
        /// </summary>
        public static string WeFreeAndFun {
            get {
                return ResourceManager.GetString("WeFreeAndFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We also have blog badges and widgets that you can install on your blog or website so your readers can get
        ///    involved in the Nerd Dinner movement. Well, it&apos;s not really a movement. Mostly just geeks in a food court, but still..
        /// </summary>
        public static string WeHaveBlogBadges {
            get {
                return ResourceManager.GetString("WeHaveBlogBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is NerdDinner.com?.
        /// </summary>
        public static string WhatIsNerdDinner {
            get {
                return ResourceManager.GetString("WhatIsNerdDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When:.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When?.
        /// </summary>
        public static string WhenQuestion {
            get {
                return ResourceManager.GetString("WhenQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where:.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where?.
        /// </summary>
        public static string WhereQuestion {
            get {
                return ResourceManager.GetString("WhereQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s Coming:.
        /// </summary>
        public static string WhosComing {
            get {
                return ResourceManager.GetString("WhosComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s Coming?.
        /// </summary>
        public static string WhosComingQuestion {
            get {
                return ResourceManager.GetString("WhosComingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why not &lt;a target=&quot;_blank&quot; href=&quot;http://www.nerddinner.com/Dinners/Create&quot;&gt;host one&lt;/a&gt;?.
        /// </summary>
        public static string WhyNotHostOne {
            get {
                return ResourceManager.GetString("WhyNotHostOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authentication is not supported..
        /// </summary>
        public static string WindowsAuthenticationNotSupported {
            get {
                return ResourceManager.GetString("WindowsAuthenticationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        public static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the host for this event!.
        /// </summary>
        public static string YouAreHostForThisEvent {
            get {
                return ResourceManager.GetString("YouAreHostForThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are registered for this event!.
        /// </summary>
        public static string YouAreRegisteredForThisEvent {
            get {
                return ResourceManager.GetString("YouAreRegisteredForThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own or aren&apos;t registered for any dinners..
        /// </summary>
        public static string YouDoNotOwnDinners {
            get {
                return ResourceManager.GetString("YouDoNotOwnDinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Don&apos;t Own This Dinner.
        /// </summary>
        public static string YouDoNotOwnThisDinner {
            get {
                return ResourceManager.GetString("YouDoNotOwnThisDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a current password..
        /// </summary>
        public static string YouMustSpecifyCurrentPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an email address..
        /// </summary>
        public static string YouMustSpecifyEmailAddress {
            get {
                return ResourceManager.GetString("YouMustSpecifyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password of {0} or more characters..
        /// </summary>
        public static string YouMustSpecifyLongerPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyLongerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password..
        /// </summary>
        public static string YouMustSpecifyPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        public static string YouMustSpecifyUsername {
            get {
                return ResourceManager.GetString("YouMustSpecifyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dinner was successfully deleted..
        /// </summary>
        public static string YourDinnerDeleted {
            get {
                return ResourceManager.GetString("YourDinnerDeleted", resourceCulture);
            }
        }
    }
}
